# --- !Ups

CREATE TABLE book_shelf
(
	SHELF_ID BIGINT AUTO_INCREMENT,
    SHELF_NAME VARCHAR(50) NOT NULL,
    SHELF_DESCRIPTION VARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    CREATED_USER VARCHAR(100) NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,
    UPDATED_USER VARCHAR(100) NOT NULL,
	PRIMARY KEY(SHELF_ID),
    INDEX(SHELF_ID),
    INDEX(SHELF_NAME)
) DEFAULT CHARSET=UTF8 ENGINE=INNODB;

# --- !Downs
DROP TABLE book_shelf;
