# --- !Ups

CREATE TABLE book_shelf
(
	SHELF_ID BIGINT AUTO_INCREMENT,
    SHELF_NAME VARCHAR(200) UNIQUE,
    SHELF_DESCRIPTION VARCHAR(400) NOT NULL,
    REGISTERED_DATE DATETIME NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,
	PRIMARY KEY(SHELF_ID),
    INDEX(SHELF_ID),
    INDEX(SHELF_NAME)
) DEFAULT CHARSET=UTF8 ENGINE=INNODB;

# --- !Downs
DROP TABLE book_shelf;
