# --- !Ups

CREATE TABLE book
(
    BOOK_ID BIGINT AUTO_INCREMENT,
    SHELF_ID BIGINT NOT NULL,
    BOOK_NAME VARCHAR(200) NOT NULL,
    BOOK_AUTHOR VARCHAR(200) NOT NULL,
    BOOK_ISBN VARCHAR(50) NOT NULL,
    LARGE_IMAGE_URL VARCHAR(300) NOT NULL,
    MEDIUM_IMAGE_URL VARCHAR(300) NOT NULL,
    SMALL_IMAGE_URL VARCHAR(300) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    CREATED_USER VARCHAR(100) NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,
    UPDATED_USER VARCHAR(100) NOT NULL,
    PRIMARY KEY(BOOK_ID),
    INDEX(SHELF_ID)
) DEFAULT CHARSET=UTF8 ENGINE=INNODB;

# --- !Downs
DROP TABLE book;
