# --- !Ups

CREATE TABLE book
(
	BOOK_ID BIGINT AUTO_INCREMENT,
    SHELF_ID BIGINT NOT NULL,
    BOOK_NAME VARCHAR(200) NOT NULL,
    BOOK_AUTHOR VARCHAR(200) NOT NULL,
    BOOK_ISBN VARCHAR(50) NOT NULL,
    REGISTERED_DATE DATETIME NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,
	PRIMARY KEY(BOOK_ID),
    INDEX(SHELF_ID)
) DEFAULT CHARSET=UTF8 ENGINE=INNODB;

# --- !Downs
DROP TABLE book;
