# --- !Ups

CREATE TABLE comment
(
	COMMENT_ID BIGINT AUTO_INCREMENT,
    TARGET_ID_TYPE INT NOT NULL,
    TARGET_ID BIGINT NOT NULL,
    COMMENT VARCHAR(1000) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    CREATED_USER VARCHAR(100) NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,
    UPDATED_USER VARCHAR(100) NOT NULL,
	PRIMARY KEY(COMMENT_ID),
    INDEX(TARGET_ID_TYPE, TARGET_ID)
) DEFAULT CHARSET=UTF8 ENGINE=INNODB;

# --- !Downs
DROP TABLE comment;
