# --- !Ups

CREATE TABLE UserInfo
(
    USER_ID BIGINT AUTO_INCREMENT,
    USER_DISPLAY_NAME VARCHAR(200) NOT NULL,
    USER_GOOGLE_ID VARCHAR(200) UNIQUE,
    USER_GOOGLE_DISPLAY_NAME VARCHAR(200) NOT NULL,
    USER_GOOGLE_PUBLIC_PROFILE_URL VARCHAR(1000) NOT NULL,
    USER_GOOGLE_PUBLIC_PROFILE_PHOTO_URL VARCHAR(1000) NOT NULL,
    USER_GOOGLE_ACCESS_TOKEN VARCHAR(300) NOT NULL,
    USER_GOOGLE_REFRESH_TOKEN VARCHAR(300),
    USER_GOOGLE_EXPIRES_AT BIGINT,
    USER_GOOGLE_EXPIRES_IN INTEGER,
    CREATED_DATE DATETIME NOT NULL,
    CREATED_USER VARCHAR(100) NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,
    UPDATED_USER VARCHAR(100) NOT NULL,
    PRIMARY KEY(USER_ID),
    INDEX(USER_GOOGLE_ID),
    INDEX(USER_DISPLAY_NAME)
) DEFAULT CHARSET=UTF8 ENGINE=INNODB;

# --- !Downs
DROP TABLE UserInfo;
