# --- !Ups

CREATE TABLE RentalInfo
(
    RENTAL_ID BIGINT AUTO_INCREMENT,
    RENTAL_USER_ID BIGINT UNIQUE,
    RENTAL_BOOK_ID BIGINT UNIQUE,
    RENTAL_NOW CHAR(1) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    CREATED_USER VARCHAR(100) NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,
    UPDATED_USER VARCHAR(100) NOT NULL,
    PRIMARY KEY(RENTAL_ID),
    INDEX(RENTAL_USER_ID)
    INDEX(RENTAL_BOOK_ID)
) DEFAULT CHARSET=UTF8 ENGINE=INNODB;

# --- !Downs
DROP TABLE RentalInfo;
