# --- !Ups

CREATE TABLE rental_info_history
(
    RENTAL_ID BIGINT NOT NULL,
    RENTAL_USER_ID BIGINT NOT NULL,
    RENTAL_BOOK_ID BIGINT NOT NULL,
    RENTAL_NOW CHAR(1) NOT NULL,
    CREATED_DATE DATETIME NOT NULL,
    CREATED_USER VARCHAR(100) NOT NULL,
    UPDATED_DATE DATETIME NOT NULL,
    UPDATED_USER VARCHAR(100) NOT NULL,
    INDEX(RENTAL_ID),
    INDEX(RENTAL_USER_ID),
    INDEX(RENTAL_BOOK_ID)
) DEFAULT CHARSET=UTF8 ENGINE=INNODB;

# --- !Downs
DROP TABLE rental_info_history;
